name: test
on:
  push:
  workflow_dispatch:

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats

env:
  TURBO_CACHE_VERSION: v0 # for cache purge

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Enable corepack for yarn
        run: corepack enable yarn

      - name: Setup & Restore Node cache
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version-file: 'package.json'

      - name: Install all packages
        run: yarn install --immutable

      - name: Restore turbo cache
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/turbo
          key:
            turbo/${{ env.TURBO_CACHE_VERSION }}/${{ github.job }}/${{ github.ref_name }}/${{ github.sha }}
          restore-keys: |
            turbo/${{ env.TURBO_CACHE_VERSION }}/${{ github.job }}/${{ github.ref_name }}/
            turbo/${{ env.TURBO_CACHE_VERSION }}/${{ github.job }}/

      - name: Lint check
        run: yarn lint

      - name: Type check
        run: yarn typecheck

      - name: Build check
        run: yarn build
